# Example route definition for a API service that delegates
# authorization to APISIX. It expects the caller to handle
# authentication on their side and present a JWT.
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: api-route
  namespace: example-service-ns
spec:
  http:
  - name: api-http-route
    match:
      hosts:
        - api-example.apx.develop.eoepca.org
      paths:
        - /*
    backends:
      - serviceName: example-service
        servicePort: 80
    plugins:
      - name: authz-keycloak
        enable: true
        config:
          client_id: "example-client"
          client_secret: "example-client-secret"
          discovery: "https://iam-auth.apx.develop.eoepca.org/realms/eoepca/.well-known/uma2-configuration"
          lazy_load_paths: true
          # ssl_verify may have to be set to false in a test environment. Not recommended for production.
          ssl_verify: false
        # refSecret is an alternative way to specify sensitive information like the client secret.
        # It is recommended to create a (sealed) secret with the same name as the route and reference it here.
        # The secret should contain the client credentials (client_id and client_secret), which may
        # then be omitted above.
        #refSecret: api-route
---
# Example secret for the route definition above.
# This secret may be referenced via refSecret instead of specifying
# the client credentials directly in the route definition.
# The secret should be created either manually or through a sealed secret.
apiVersion: v1
data:
  client_id: "ZXhhbXBsZS1jbGllbnQ="
  client_secret: "ZXhhbXBsZS1jbGllbnQtc2VjcmV0"
kind: Secret
metadata:
  # Secret name should match route name.
  name: api-route
  namespace: example-service-ns
type: Opaque
