# Example Plugin Config
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: example-plugin-config
  namespace: example-ns
spec:
  plugins:
    - name: openid-connect
      enable: true
      config:
        access_token_in_authorization_header: true
        bearer_only: false
        discovery: https://iam-auth.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration
      secretRef: example-plugin-config
