# Example route definition for a service that offers paths with
# different protection. The route below defined the following
# subroutes:
# - /index.html, /public and /public/* (simple pass-through, specified by regex)
# - /api/* (API protection)
# - /* (everything else: full protection)
# Furthermore, in this example the client credentials are
# omitted and specified through a secret.
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: mixed-route
  namespace: example-service-ns
spec:
  http:
  - name: public-http-route
    backends:
      - serviceName: example-service
        servicePort: 80
    match:
      hosts:
        - mixed-example.apx.develop.eoepca.org
      paths:
        - /*
      exprs:
        - subject:
            scope: Path
          op: RegexMatch
          value: "^/(index.html|public(/.*)?)"
  - name: api-http-route
    backends:
      - serviceName: example-service
        servicePort: 80
    match:
      hosts:
        - mixed-example.apx.develop.eoepca.org
      paths:
        - /api/*
    plugins:
      - name: openid-connect
        enable: true
        config:
          access_token_in_authorization_header: true
          # Only validate the JWT and report 401 on failure; do not trigger authN flow
          bearer_only: true
          discovery: "https://iam-auth.apx.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
        secretRef: mixed-route
      - name: authz-keycloak
        enable: true
        config:
          discovery: "https://iam-auth.apx.develop.eoepca.org/realms/eoepca/.well-known/uma2-configuration"
          lazy_load_paths: true
          # ssl_verify may have to be set to false in a test environment. Not recommended for production.
          ssl_verify: false
        secretRef: mixed-route
  - name: default-http-route
    backends:
      - serviceName: example-service
        servicePort: 80
    match:
      hosts:
        - mixed-example.apx.develop.eoepca.org
      paths:
        - /*
    plugins:
      - name: openid-connect
        enable: true
        config:
          access_token_in_authorization_header: true
          discovery: "https://iam-auth.apx.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration"
        secretRef: mixed-route
      - name: authz-keycloak
        enable: true
        config:
          discovery: "https://iam-auth.apx.develop.eoepca.org/realms/eoepca/.well-known/uma2-configuration"
          lazy_load_paths: true
          # ssl_verify may have to be set to false in a test environment. Not recommended for production.
          ssl_verify: false
        secretRef: mixed-route
---
# Example secret for the route definition above.
# This secret is referenced via secretRef instead of specifying
# the client credentials directly in the route definition.
# The secret should be created either manually or through a sealed secret.
apiVersion: v1
data:
  client_id: "ZXhhbXBsZS1jbGllbnQ="
  client_secret: "ZXhhbXBsZS1jbGllbnQtc2VjcmV0"
kind: Secret
metadata:
  # Secret name should match route name.
  name: mixed-route
  namespace: example-service-ns
type: Opaque
