{{ if .Values.iam.opa.enabled -}}
{{ if .Values.iam.opa.createRoute -}}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: opa-route
spec:
  http:
  - name: opa
    match:
      hosts: {{- .Values.iam.opa.hosts | toYaml | nindent 6 }}
      paths: {{- .Values.iam.opa.paths | toYaml | nindent 6 }}
    backends:
      - serviceName: iam-opal-client
        servicePort: 8181
    plugins:
      - name: openid-connect
        enable: true
        config:
          client_id: {{ .Values.iam.opa.clientId | quote }}
{{- if .Values.iam.opa.clientSecret }}
          client_secret: {{ .Values.iam.opa.clientSecret | quote }}
{{- end }}
          access_token_in_authorization_header: true
          discovery: "{{ .Values.iam.keycloak.url }}/realms/eoepca/.well-known/openid-configuration"
{{- if .Values.iam.opa.clientSecretRef }}
        refSecret: {{ .Values.iam.opa.clientSecretRef | quote }}
{{- end }}
      - name: authz-keycloak
        enable: true
        config:
          client_id: {{ .Values.iam.opa.clientId | quote }}
{{- if .Values.iam.opa.clientSecret }}
          client_secret: {{ .Values.iam.opa.clientSecret | quote }}
{{- end }}
          discovery: "{{ .Values.iam.keycloak.url }}/realms/eoepca/.well-known/uma2-configuration"
          #permissions: "Resource all"
          lazy_load_paths: true
          # ssl_verify may have to be set to false in a test environment. Not recommended for production.
          ssl_verify: false
{{- if .Values.iam.opa.clientSecretRef }}
        refSecret: {{ .Values.iam.opa.clientSecretRef | quote }}
{{- end }}
{{- end }}
{{- end }}