{{ if .Values.iam.identityApi.enabled -}}
{{ if .Values.iam.identityApi.createRoute -}}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: identity-api-route
spec:
  http:
{{- if .Values.iam.identityApi.docsPath }}
  - name: identity-api-docs
    match:
      hosts: {{- .Values.iam.identityApi.hosts | toYaml | nindent 6 }}
      paths:
        - {{ .Values.iam.identityApi.docsPath | quote }}
    backends:
      - serviceName: identity-api
        servicePort: 8080
    plugins:
      - name: openid-connect
        enable: true
        config:
          client_id: {{ .Values.iam.identityApi.clientId | quote }}
{{- if .Values.iam.identityApi.clientSecret }}
          client_secret: {{ .Values.iam.identityApi.clientSecret | quote }}
{{- end }}
          access_token_in_authorization_header: true
          discovery: "{{ .Values.iam.keycloak.url }}/realms/eoepca/.well-known/openid-configuration"
{{- if .Values.iam.identityApi.clientSecretRef }}
        refSecret: {{ .Values.iam.identityApi.clientSecretRef | quote }}
{{- end }}
      - name: authz-keycloak
        enable: true
        config:
          client_id: {{ .Values.iam.identityApi.clientId | quote }}
{{- if .Values.iam.identityApi.clientSecret }}
          client_secret: {{ .Values.iam.identityApi.clientSecret | quote }}
{{- end }}
          discovery: "{{ .Values.iam.keycloak.url }}/realms/eoepca/.well-known/uma2-configuration"
          #permissions: "Resource all"
          lazy_load_paths: true
          # ssl_verify may have to be set to false in a test environment. Not recommended for production.
          ssl_verify: false
{{- if .Values.iam.identityApi.clientSecretRef }}
        refSecret: {{ .Values.iam.identityApi.clientSecretRef | quote }}
{{- end -}}
{{- end }}
  - name: identity-api
    match:
      hosts: {{- .Values.iam.identityApi.hosts | toYaml | nindent 6 }}
      paths: {{- .Values.iam.identityApi.paths | toYaml | nindent 6 }}
    backends:
      - serviceName: identity-api
        servicePort: 8080
    plugins:
      - name: openid-connect
        enable: false
        config:
          client_id: {{ .Values.iam.identityApi.clientId | quote }}
{{- if .Values.iam.identityApi.clientSecret }}
          client_secret: {{ .Values.iam.identityApi.clientSecret | quote }}
{{- end }}
          access_token_in_authorization_header: true
          discovery: "{{ .Values.iam.keycloak.url }}/realms/eoepca/.well-known/openid-configuration"
{{- if .Values.iam.identityApi.clientSecretRef }}
        refSecret: {{ .Values.iam.identityApi.clientSecretRef | quote }}
{{- end }}
      - name: authz-keycloak
        enable: true
        config:
          client_id: {{ .Values.iam.identityApi.clientId | quote }}
{{- if .Values.iam.identityApi.clientSecret }}
          client_secret: {{ .Values.iam.identityApi.clientSecret | quote }}
{{- end }}
          discovery: "{{ .Values.iam.keycloak.url }}/realms/eoepca/.well-known/uma2-configuration"
          #permissions: "Resource all"
          lazy_load_paths: true
          # ssl_verify may have to be set to false in a test environment. Not recommended for production.
          ssl_verify: false
{{- if .Values.iam.identityApi.clientSecretRef }}
        refSecret: {{ .Values.iam.identityApi.clientSecretRef | quote }}
{{- end }}
{{- end }}
{{- end }}