{{ if .Values.iam.apisix.enabled -}}
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: redirect-to-tls
spec:
  plugins:
    - name: redirect
      enable: true
      config:
        http_to_https: true
        _meta:
          filter:
            # Exclude paths used by letsencrypt http challenge
            - [ 'request_uri', '!', '~*', '^/\.well-known/acme-challenge.*' ]
{{- end }}