{{ if .Values.iam.identityApi.enabled -}}
{{ if .Values.iam.identityApi.createRoute -}}
{{ if .Values.iam.identityApi.clientSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: identity-api-route
  namespace: {{ .Release.Namespace }}
data:
  client_id: "{{ .Values.iam.identityApi.clientId | b64enc }}"
  client_secret: "{{ .Values.iam.identityApi.clientSecret | b64enc }}"
{{- end }}
{{- end }}
{{- end }}