{{ if .Values.iam.opa.enabled -}}
{{ if .Values.iam.opa.createRoute -}}
{{ if .Values.iam.opa.clientSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: opa-route
  namespace: {{ .Release.Namespace }}
data:
  client_id: "{{ .Values.iam.opa.clientId | b64enc }}"
  client_secret: "{{ .Values.iam.opa.clientSecret | b64enc }}"
{{- end }}
{{- end }}
{{- end }}