apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: opa
spec:
  http:
  - name: opa
    match:
      hosts:
      - opa.172.30.170.97.nip.io
      paths:
      - /*
    backends:
    - serviceName: opal-client
      servicePort: 8181
    plugins:
    - name: openid-connect
      enable: true
      config:
        client_id: "opa"
        client_secret: "pbTYupZ8OLktAwsbRz6QVoHNEtFH9Uwx"
        #bearer_only: true
        #realm: "eoepca"
        #redirect_uri: "http://opa.172.30.170.97.nip.io/"
        access_token_in_authorization_header: true
        discovery: "http://keycloak.172.30.170.97.nip.io/realms/eoepca/.well-known/openid-configuration"
    - name: authz-keycloak
      enable: true
      config:
        client_id: "opa"
        client_secret: "pbTYupZ8OLktAwsbRz6QVoHNEtFH9Uwx"
        discovery: "http://keycloak.172.30.170.97.nip.io/realms/eoepca/.well-known/uma2-configuration"
        #permissions: "Resource all"
        lazy_load_paths: true
        ssl_verify: false
