apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpd
spec:
  http:
  - name: httpd
    match:
      hosts:
      - "%hostname%"
      paths:
      - /*
    backends:
    - serviceName: httpd
      servicePort: 80
    plugins:
    - name: openid-connect
      enable: true
      config:
        client_id: 
        client_secret: 
        access_token_in_authorization_header: true
        discovery: "path/to/.well-known/openid-configuration"
    - name: authz-keycloak
      enable: true
      config:
        client_id: 
        client_secret: 
        discovery: "path/to/.well-known/uma2-configuration"
        #permissions: "Resource all"
        lazy_load_paths: true
