# Example route definition for Keycloak
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: keycloak-route
  namespace: iam
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  http:
  - backends:
    - serviceName: iam-keycloak
      servicePort: 80
    match:
      hosts:
      - iam-auth.apx.develop.eoepca.org
      paths:
      - /*
    name: keycloak
    plugins:
      # Possible workaround for redirect-to-9443 problem that also works for HTTP
      - name: serverless-pre-function
        enable: true
        config:
          phase: "rewrite"
          functions:
            - "return function(conf, ctx) if tonumber(ngx.var.var_x_forwarded_port) > 9000 then ngx.var.var_x_forwarded_port = ngx.var.var_x_forwarded_port - 9000 end end"
